### ISSUE TITLE
Commands not visible

### ISSUE THREAD

**Issue by DugarRishab** [sereneinserenade/notetap#16]
I tried opening the command menu using forward-slash method and it does work. Moreover I also tried to open it using the "+" sign, and it still does not work. I cant get it to open.

**Comment by sereneinserenade** [comment]
@DugarRishab Hi, thanks for letting me know, I am aware that it doesn't work and I'll be fixing it soon.

**Comment by sereneinserenade** [comment]
to anyone visiting in future. Visit [placenoter](https://github.com/sereneinserenade/placenoter/tree/main/src/components/editor/extensions/slash-menu) for an implementation of slash menu. [Live demo](https://sereneinserenade.github.io/placenoter/)
