### ISSUE TITLE
Slash Command is not working

### ISSUE THREAD

**Issue by vigneshrams** [sereneinserenade/notetap#17]
Hi @sereneinserenade,
How do I enable the slash command here? Please help me set it up with the NExtJS application

**Comment by sereneinserenade** [comment]
Hey @vigneshrams please have a look at [placenoter](https://github.com/sereneinserenade/placenoter/tree/main/src/components/editor/extensions/slash-menu) there you'll find a full react implementation of slash-menu. You can also [try it out](https://sereneinserenade.github.io/placenoter/).
